services:
  # The Flask Web Application
  - type: web
    name: plotplus-web
    plan: free # Free tier or upgrade
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true # Render will securely generate a random string for you automatically
